OCCUPATION_CHOICES = [
    ('LTD', 'Listed Companies'),
    ('FIN', 'Finance'),
    ('CIV', 'Civics'),
    ('CON', 'Consulting'),
    ('MGR', 'Managers and Executives'),
    ('LGE', 'Large companies'),
    ('MFC', 'Major foreign companies'),
    ('MTC', 'Major trading company'),
    ('FFN', 'Foreign Finance'),
    ('DOC', 'Doctor'),
    ('NUR', 'Nurse'),
    ('PHR', 'Pharmacist'),
    ('LAW', 'Lawyer'),
    ('JSC', 'Judicial scrivener'),
    ('ASC', 'Administrative scrivener'),
    ('PAT', 'Patent Attorney'),
    ('SIW', 'Social insurance worker'),
    ('CPA', 'Certified Public Accountant'),
    ('PIL', 'Pilot'),
    ('FA', 'Flight attendant'),
    ('ADV', 'Advertisement'),
    ('MED', 'Media'),
    ('EDU', 'Education'),
    ('IT', 'IT-related'),
    ('FR', 'Food related'),
    ('TRV', 'Travel'),
    ('PHM', 'Pharmaceuticals'),
    ('INS', 'Insurance'),
    ('RE', 'Real estate'),
    ('ARC', 'Architecture'),
    ('COM', 'Communication'),
    ('DIS', 'Distribution'),
    ('WEB', 'Web industry'),
    ('BRD', 'Bridal'),
    ('HOS', 'Hospitality'),
    ('CRT', 'Creator'),
    ('REC', 'Reception'),
    ('CHE', 'Chef/Nutritionist'),
    ('APP', 'Apparel'),
    ('BEA', 'Beauty related'),
    ('ENT', 'Entertainment'),
    ('ANN', 'Announcer'),
    ('MOD', 'Entertainment/Model'),
    ('EC', 'Event Companion'),
    ('ATH', 'Athletes'),
    ('SEC', 'Secretary'),
    ('CLK', 'Clerk'),
    ('WEL', 'Welfare and nursing care'),
    ('NT', 'Nursery teacher'),
    ('EMP', 'Company employee'),
    ('STU', 'Students'),
    ('FRL', 'Freelance'),
    ('TAX', 'Tax accountant'),
    ('ENG', 'Engineer'),
    ('ARC', 'Architect'),
    ('HRD', 'Hairdresser'),
    ('DEN', 'Dentist'),
    ('DHY', 'Dental hygienist'),
    ('OTH', 'Others'),
]

BODY_TYPE_CHOICES = [
    ('SL', 'Slim'),
    ('AV', 'Average'),
    ('ATH', 'Athletic'),
    ('OV', 'Overweight'),
    ('OB', 'Obese'),
    ('OT', 'Other'),
]

MARRIED_CHOICES = [
    ('M', 'Married'),
    ('S', 'Single'),
]

HIGHEST_EDUCATION_CHOICES = [
    ('HS', 'High School'),
    ('BA', 'Bachelor\'s Degree'),
    ('MA', 'Master\'s Degree'),
    ('PHD', 'Doctorate'),
    ('OT', 'Other'),
]
